apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-chart.fullname" . }}-config
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
data:
  app_config.ini: |
    [DEFAULT]
    debug = false
    log_level = INFO

